// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module TOP_TOP_Pipeline_VITIS_LOOP_492_5_VITIS_LOOP_493_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        H_rvd_address0,
        H_rvd_ce0,
        H_rvd_q0,
        HH_V_29_1_out,
        HH_V_29_1_out_ap_vld,
        HH_V_28_1_out,
        HH_V_28_1_out_ap_vld,
        HH_V_27_1_out,
        HH_V_27_1_out_ap_vld,
        HH_V_26_1_out,
        HH_V_26_1_out_ap_vld,
        HH_V_25_1_out,
        HH_V_25_1_out_ap_vld,
        HH_V_24_1_out,
        HH_V_24_1_out_ap_vld,
        HH_V_23_1_out,
        HH_V_23_1_out_ap_vld,
        HH_V_22_1_out,
        HH_V_22_1_out_ap_vld,
        HH_V_21_1_out,
        HH_V_21_1_out_ap_vld,
        HH_V_20_1_out,
        HH_V_20_1_out_ap_vld,
        HH_V_19_1_out,
        HH_V_19_1_out_ap_vld,
        HH_V_18_1_out,
        HH_V_18_1_out_ap_vld,
        HH_V_17_1_out,
        HH_V_17_1_out_ap_vld,
        HH_V_16_1_out,
        HH_V_16_1_out_ap_vld,
        HH_V_15_1_out,
        HH_V_15_1_out_ap_vld,
        HH_V_14_1_out,
        HH_V_14_1_out_ap_vld,
        HH_V_13_1_out,
        HH_V_13_1_out_ap_vld,
        HH_V_12_1_out,
        HH_V_12_1_out_ap_vld,
        HH_V_11_1_out,
        HH_V_11_1_out_ap_vld,
        HH_V_10_1_out,
        HH_V_10_1_out_ap_vld,
        HH_V_9_1_out,
        HH_V_9_1_out_ap_vld,
        HH_V_8_1_out,
        HH_V_8_1_out_ap_vld,
        HH_V_7_1_out,
        HH_V_7_1_out_ap_vld,
        HH_V_6_1_out,
        HH_V_6_1_out_ap_vld,
        HH_V_5_1_out,
        HH_V_5_1_out_ap_vld,
        HH_V_4_1_out,
        HH_V_4_1_out_ap_vld,
        HH_V_3_1_out,
        HH_V_3_1_out_ap_vld,
        HH_V_2_1_out,
        HH_V_2_1_out_ap_vld,
        HH_V_1_1_out,
        HH_V_1_1_out_ap_vld,
        HH_V_141_out,
        HH_V_141_out_ap_vld,
        HH_V_30_1_out,
        HH_V_30_1_out_ap_vld,
        HH_V_31_1_out,
        HH_V_31_1_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] H_rvd_address0;
output   H_rvd_ce0;
input  [63:0] H_rvd_q0;
output  [15:0] HH_V_29_1_out;
output   HH_V_29_1_out_ap_vld;
output  [15:0] HH_V_28_1_out;
output   HH_V_28_1_out_ap_vld;
output  [15:0] HH_V_27_1_out;
output   HH_V_27_1_out_ap_vld;
output  [15:0] HH_V_26_1_out;
output   HH_V_26_1_out_ap_vld;
output  [15:0] HH_V_25_1_out;
output   HH_V_25_1_out_ap_vld;
output  [15:0] HH_V_24_1_out;
output   HH_V_24_1_out_ap_vld;
output  [15:0] HH_V_23_1_out;
output   HH_V_23_1_out_ap_vld;
output  [15:0] HH_V_22_1_out;
output   HH_V_22_1_out_ap_vld;
output  [15:0] HH_V_21_1_out;
output   HH_V_21_1_out_ap_vld;
output  [15:0] HH_V_20_1_out;
output   HH_V_20_1_out_ap_vld;
output  [15:0] HH_V_19_1_out;
output   HH_V_19_1_out_ap_vld;
output  [15:0] HH_V_18_1_out;
output   HH_V_18_1_out_ap_vld;
output  [15:0] HH_V_17_1_out;
output   HH_V_17_1_out_ap_vld;
output  [15:0] HH_V_16_1_out;
output   HH_V_16_1_out_ap_vld;
output  [15:0] HH_V_15_1_out;
output   HH_V_15_1_out_ap_vld;
output  [15:0] HH_V_14_1_out;
output   HH_V_14_1_out_ap_vld;
output  [15:0] HH_V_13_1_out;
output   HH_V_13_1_out_ap_vld;
output  [15:0] HH_V_12_1_out;
output   HH_V_12_1_out_ap_vld;
output  [15:0] HH_V_11_1_out;
output   HH_V_11_1_out_ap_vld;
output  [15:0] HH_V_10_1_out;
output   HH_V_10_1_out_ap_vld;
output  [15:0] HH_V_9_1_out;
output   HH_V_9_1_out_ap_vld;
output  [15:0] HH_V_8_1_out;
output   HH_V_8_1_out_ap_vld;
output  [15:0] HH_V_7_1_out;
output   HH_V_7_1_out_ap_vld;
output  [15:0] HH_V_6_1_out;
output   HH_V_6_1_out_ap_vld;
output  [15:0] HH_V_5_1_out;
output   HH_V_5_1_out_ap_vld;
output  [15:0] HH_V_4_1_out;
output   HH_V_4_1_out_ap_vld;
output  [15:0] HH_V_3_1_out;
output   HH_V_3_1_out_ap_vld;
output  [15:0] HH_V_2_1_out;
output   HH_V_2_1_out_ap_vld;
output  [15:0] HH_V_1_1_out;
output   HH_V_1_1_out_ap_vld;
output  [15:0] HH_V_141_out;
output   HH_V_141_out_ap_vld;
output  [15:0] HH_V_30_1_out;
output   HH_V_30_1_out_ap_vld;
output  [15:0] HH_V_31_1_out;
output   HH_V_31_1_out_ap_vld;

reg ap_idle;
reg H_rvd_ce0;
reg HH_V_29_1_out_ap_vld;
reg HH_V_28_1_out_ap_vld;
reg HH_V_27_1_out_ap_vld;
reg HH_V_26_1_out_ap_vld;
reg HH_V_25_1_out_ap_vld;
reg HH_V_24_1_out_ap_vld;
reg HH_V_23_1_out_ap_vld;
reg HH_V_22_1_out_ap_vld;
reg HH_V_21_1_out_ap_vld;
reg HH_V_20_1_out_ap_vld;
reg HH_V_19_1_out_ap_vld;
reg HH_V_18_1_out_ap_vld;
reg HH_V_17_1_out_ap_vld;
reg HH_V_16_1_out_ap_vld;
reg HH_V_15_1_out_ap_vld;
reg HH_V_14_1_out_ap_vld;
reg HH_V_13_1_out_ap_vld;
reg HH_V_12_1_out_ap_vld;
reg HH_V_11_1_out_ap_vld;
reg HH_V_10_1_out_ap_vld;
reg HH_V_9_1_out_ap_vld;
reg HH_V_8_1_out_ap_vld;
reg HH_V_7_1_out_ap_vld;
reg HH_V_6_1_out_ap_vld;
reg HH_V_5_1_out_ap_vld;
reg HH_V_4_1_out_ap_vld;
reg HH_V_3_1_out_ap_vld;
reg HH_V_2_1_out_ap_vld;
reg HH_V_1_1_out_ap_vld;
reg HH_V_141_out_ap_vld;
reg HH_V_30_1_out_ap_vld;
reg HH_V_31_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln492_fu_576_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] icmp_ln492_reg_1353;
wire    ap_block_pp0_stage0_11001;
wire   [2:0] trunc_ln492_fu_622_p1;
reg   [2:0] trunc_ln492_reg_1357;
wire   [1:0] trunc_ln494_fu_626_p1;
reg   [1:0] trunc_ln494_reg_1361;
reg   [15:0] ap_phi_mux_HH_V_phi_fu_542_p12;
wire   [15:0] trunc_ln592_fu_847_p1;
wire   [15:0] ap_phi_reg_pp0_iter1_HH_V_reg_539;
wire   [0:0] icmp_ln580_fu_726_p2;
wire   [0:0] icmp_ln591_fu_768_p2;
wire   [15:0] select_ln597_fu_819_p3;
wire   [0:0] icmp_ln590_fu_738_p2;
wire   [0:0] icmp_ln594_fu_805_p2;
wire   [15:0] trunc_ln595_1_fu_842_p1;
wire   [15:0] shl_ln613_fu_798_p2;
wire   [0:0] icmp_ln612_fu_788_p2;
wire   [63:0] zext_ln494_fu_640_p1;
wire    ap_block_pp0_stage0;
reg   [2:0] j_fu_162;
wire   [2:0] add_ln493_fu_645_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_j_load;
reg   [3:0] i_fu_166;
wire   [3:0] select_ln492_1_fu_614_p3;
reg   [3:0] ap_sig_allocacmp_i_load;
reg   [5:0] indvar_flatten7_fu_170;
wire   [5:0] add_ln492_1_fu_582_p2;
reg   [5:0] ap_sig_allocacmp_indvar_flatten7_load;
reg   [15:0] HH_V_1_fu_174;
reg   [15:0] HH_V_2_fu_178;
reg   [15:0] HH_V_3_fu_182;
reg   [15:0] HH_V_4_fu_186;
reg   [15:0] HH_V_5_fu_190;
reg   [15:0] HH_V_6_fu_194;
reg   [15:0] HH_V_7_fu_198;
reg   [15:0] HH_V_8_fu_202;
reg   [15:0] HH_V_9_fu_206;
reg   [15:0] HH_V_10_fu_210;
reg   [15:0] HH_V_11_fu_214;
reg   [15:0] HH_V_12_fu_218;
reg   [15:0] HH_V_13_fu_222;
reg   [15:0] HH_V_14_fu_226;
reg   [15:0] HH_V_15_fu_230;
reg   [15:0] HH_V_16_fu_234;
reg   [15:0] HH_V_17_fu_238;
reg   [15:0] HH_V_18_fu_242;
reg   [15:0] HH_V_19_fu_246;
reg   [15:0] HH_V_20_fu_250;
reg   [15:0] HH_V_21_fu_254;
reg   [15:0] HH_V_22_fu_258;
reg   [15:0] HH_V_23_fu_262;
reg   [15:0] HH_V_24_fu_266;
reg   [15:0] HH_V_25_fu_270;
reg   [15:0] HH_V_26_fu_274;
reg   [15:0] HH_V_27_fu_278;
reg   [15:0] HH_V_28_fu_282;
reg   [15:0] HH_V_29_fu_286;
reg   [15:0] HH_V_30_fu_290;
reg   [15:0] HH_V_31_fu_294;
reg   [15:0] HH_V_32_fu_298;
wire    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln493_fu_600_p2;
wire   [3:0] add_ln492_fu_594_p2;
wire   [2:0] select_ln492_fu_606_p3;
wire   [6:0] tmp_2_fu_630_p4;
wire   [63:0] ireg_fu_666_p1;
wire   [10:0] exp_tmp_fu_682_p4;
wire   [51:0] trunc_ln574_fu_696_p1;
wire   [52:0] p_Result_1_fu_700_p3;
wire   [53:0] zext_ln578_fu_708_p1;
wire   [0:0] p_Result_s_fu_674_p3;
wire   [53:0] man_V_1_fu_712_p2;
wire   [62:0] trunc_ln564_fu_670_p1;
wire   [11:0] zext_ln501_fu_692_p1;
wire   [11:0] F2_fu_732_p2;
wire   [11:0] add_ln590_fu_744_p2;
wire   [11:0] sub_ln590_fu_750_p2;
wire  signed [11:0] sh_amt_fu_756_p3;
wire   [53:0] man_V_2_fu_718_p3;
wire   [7:0] tmp_fu_778_p4;
wire  signed [30:0] sext_ln590_fu_764_p1;
wire   [15:0] trunc_ln611_fu_774_p1;
wire   [15:0] sext_ln590cast_fu_794_p1;
wire   [0:0] tmp_1_fu_811_p3;
wire   [5:0] trunc_ln595_fu_828_p1;
wire   [53:0] zext_ln595_fu_832_p1;
wire   [53:0] ashr_ln595_fu_836_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

TOP_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln492_fu_576_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_166 <= select_ln492_1_fu_614_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_166 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln492_fu_576_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten7_fu_170 <= add_ln492_1_fu_582_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten7_fu_170 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln492_fu_576_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_162 <= add_ln493_fu_645_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_162 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd3) & (trunc_ln492_reg_1357 == 3'd1))) begin
        HH_V_10_fu_210 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd0) & (trunc_ln492_reg_1357 == 3'd2))) begin
        HH_V_11_fu_214 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd1) & (trunc_ln492_reg_1357 == 3'd2))) begin
        HH_V_12_fu_218 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd2) & (trunc_ln492_reg_1357 == 3'd2))) begin
        HH_V_13_fu_222 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd3) & (trunc_ln492_reg_1357 == 3'd2))) begin
        HH_V_14_fu_226 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd0) & (trunc_ln492_reg_1357 == 3'd3))) begin
        HH_V_15_fu_230 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd1) & (trunc_ln492_reg_1357 == 3'd3))) begin
        HH_V_16_fu_234 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd2) & (trunc_ln492_reg_1357 == 3'd3))) begin
        HH_V_17_fu_238 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd3) & (trunc_ln492_reg_1357 == 3'd3))) begin
        HH_V_18_fu_242 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd0) & (trunc_ln492_reg_1357 == 3'd4))) begin
        HH_V_19_fu_246 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd3) & (trunc_ln492_reg_1357 == 3'd7))) begin
        HH_V_1_fu_174 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd1) & (trunc_ln492_reg_1357 == 3'd4))) begin
        HH_V_20_fu_250 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd2) & (trunc_ln492_reg_1357 == 3'd4))) begin
        HH_V_21_fu_254 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd3) & (trunc_ln492_reg_1357 == 3'd4))) begin
        HH_V_22_fu_258 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd0) & (trunc_ln492_reg_1357 == 3'd5))) begin
        HH_V_23_fu_262 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd1) & (trunc_ln492_reg_1357 == 3'd5))) begin
        HH_V_24_fu_266 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd2) & (trunc_ln492_reg_1357 == 3'd5))) begin
        HH_V_25_fu_270 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd3) & (trunc_ln492_reg_1357 == 3'd5))) begin
        HH_V_26_fu_274 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd0) & (trunc_ln492_reg_1357 == 3'd6))) begin
        HH_V_27_fu_278 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd1) & (trunc_ln492_reg_1357 == 3'd6))) begin
        HH_V_28_fu_282 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd2) & (trunc_ln492_reg_1357 == 3'd6))) begin
        HH_V_29_fu_286 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd2) & (trunc_ln492_reg_1357 == 3'd7))) begin
        HH_V_2_fu_178 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd3) & (trunc_ln492_reg_1357 == 3'd6))) begin
        HH_V_30_fu_290 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd0) & (trunc_ln492_reg_1357 == 3'd7))) begin
        HH_V_31_fu_294 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd1) & (trunc_ln492_reg_1357 == 3'd7))) begin
        HH_V_32_fu_298 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd0) & (trunc_ln492_reg_1357 == 3'd0))) begin
        HH_V_3_fu_182 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd1) & (trunc_ln492_reg_1357 == 3'd0))) begin
        HH_V_4_fu_186 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd2) & (trunc_ln492_reg_1357 == 3'd0))) begin
        HH_V_5_fu_190 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd3) & (trunc_ln492_reg_1357 == 3'd0))) begin
        HH_V_6_fu_194 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd0) & (trunc_ln492_reg_1357 == 3'd1))) begin
        HH_V_7_fu_198 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd1) & (trunc_ln492_reg_1357 == 3'd1))) begin
        HH_V_8_fu_202 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln494_reg_1361 == 2'd2) & (trunc_ln492_reg_1357 == 3'd1))) begin
        HH_V_9_fu_206 <= ap_phi_mux_HH_V_phi_fu_542_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln492_reg_1353 <= icmp_ln492_fu_576_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln492_fu_576_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln492_reg_1357 <= trunc_ln492_fu_622_p1;
        trunc_ln494_reg_1361 <= trunc_ln494_fu_626_p1;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_10_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_10_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_11_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_11_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_12_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_12_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_13_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_13_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_141_out_ap_vld = 1'b1;
    end else begin
        HH_V_141_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_14_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_14_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_15_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_15_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_16_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_16_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_17_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_17_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_18_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_18_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_19_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_19_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_1_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_1_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_20_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_20_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_21_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_21_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_22_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_22_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_23_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_23_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_24_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_24_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_25_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_25_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_26_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_26_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_27_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_27_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_28_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_28_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_29_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_29_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_2_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_2_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_30_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_30_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_31_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_31_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_3_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_3_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_4_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_4_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_5_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_5_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_6_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_6_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_7_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_7_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_8_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_8_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HH_V_9_1_out_ap_vld = 1'b1;
    end else begin
        HH_V_9_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        H_rvd_ce0 = 1'b1;
    end else begin
        H_rvd_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln492_fu_576_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln580_fu_726_p2 == 1'd1) & (icmp_ln492_reg_1353 == 1'd0)) | ((icmp_ln612_fu_788_p2 == 1'd0) & (icmp_ln590_fu_738_p2 == 1'd0) & (icmp_ln591_fu_768_p2 == 1'd0) & (icmp_ln580_fu_726_p2 == 1'd0) & (icmp_ln492_reg_1353 == 1'd0)))) begin
        ap_phi_mux_HH_V_phi_fu_542_p12 = 16'd0;
    end else if (((icmp_ln612_fu_788_p2 == 1'd1) & (icmp_ln590_fu_738_p2 == 1'd0) & (icmp_ln591_fu_768_p2 == 1'd0) & (icmp_ln580_fu_726_p2 == 1'd0) & (icmp_ln492_reg_1353 == 1'd0))) begin
        ap_phi_mux_HH_V_phi_fu_542_p12 = shl_ln613_fu_798_p2;
    end else if (((icmp_ln594_fu_805_p2 == 1'd1) & (icmp_ln590_fu_738_p2 == 1'd1) & (icmp_ln591_fu_768_p2 == 1'd0) & (icmp_ln580_fu_726_p2 == 1'd0) & (icmp_ln492_reg_1353 == 1'd0))) begin
        ap_phi_mux_HH_V_phi_fu_542_p12 = trunc_ln595_1_fu_842_p1;
    end else if (((icmp_ln594_fu_805_p2 == 1'd0) & (icmp_ln590_fu_738_p2 == 1'd1) & (icmp_ln591_fu_768_p2 == 1'd0) & (icmp_ln580_fu_726_p2 == 1'd0) & (icmp_ln492_reg_1353 == 1'd0))) begin
        ap_phi_mux_HH_V_phi_fu_542_p12 = select_ln597_fu_819_p3;
    end else if (((icmp_ln591_fu_768_p2 == 1'd1) & (icmp_ln580_fu_726_p2 == 1'd0) & (icmp_ln492_reg_1353 == 1'd0))) begin
        ap_phi_mux_HH_V_phi_fu_542_p12 = trunc_ln592_fu_847_p1;
    end else begin
        ap_phi_mux_HH_V_phi_fu_542_p12 = ap_phi_reg_pp0_iter1_HH_V_reg_539;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_load = 4'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_166;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten7_load = 6'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten7_load = indvar_flatten7_fu_170;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_load = 3'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_162;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign F2_fu_732_p2 = (12'd1075 - zext_ln501_fu_692_p1);

assign HH_V_10_1_out = HH_V_13_fu_222;

assign HH_V_11_1_out = HH_V_14_fu_226;

assign HH_V_12_1_out = HH_V_15_fu_230;

assign HH_V_13_1_out = HH_V_16_fu_234;

assign HH_V_141_out = HH_V_3_fu_182;

assign HH_V_14_1_out = HH_V_17_fu_238;

assign HH_V_15_1_out = HH_V_18_fu_242;

assign HH_V_16_1_out = HH_V_19_fu_246;

assign HH_V_17_1_out = HH_V_20_fu_250;

assign HH_V_18_1_out = HH_V_21_fu_254;

assign HH_V_19_1_out = HH_V_22_fu_258;

assign HH_V_1_1_out = HH_V_4_fu_186;

assign HH_V_20_1_out = HH_V_23_fu_262;

assign HH_V_21_1_out = HH_V_24_fu_266;

assign HH_V_22_1_out = HH_V_25_fu_270;

assign HH_V_23_1_out = HH_V_26_fu_274;

assign HH_V_24_1_out = HH_V_27_fu_278;

assign HH_V_25_1_out = HH_V_28_fu_282;

assign HH_V_26_1_out = HH_V_29_fu_286;

assign HH_V_27_1_out = HH_V_30_fu_290;

assign HH_V_28_1_out = HH_V_31_fu_294;

assign HH_V_29_1_out = HH_V_32_fu_298;

assign HH_V_2_1_out = HH_V_5_fu_190;

assign HH_V_30_1_out = HH_V_2_fu_178;

assign HH_V_31_1_out = HH_V_1_fu_174;

assign HH_V_3_1_out = HH_V_6_fu_194;

assign HH_V_4_1_out = HH_V_7_fu_198;

assign HH_V_5_1_out = HH_V_8_fu_202;

assign HH_V_6_1_out = HH_V_9_fu_206;

assign HH_V_7_1_out = HH_V_10_fu_210;

assign HH_V_8_1_out = HH_V_11_fu_214;

assign HH_V_9_1_out = HH_V_12_fu_218;

assign H_rvd_address0 = zext_ln494_fu_640_p1;

assign add_ln492_1_fu_582_p2 = (ap_sig_allocacmp_indvar_flatten7_load + 6'd1);

assign add_ln492_fu_594_p2 = (ap_sig_allocacmp_i_load + 4'd1);

assign add_ln493_fu_645_p2 = (select_ln492_fu_606_p3 + 3'd1);

assign add_ln590_fu_744_p2 = ($signed(F2_fu_732_p2) + $signed(12'd4088));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter1_HH_V_reg_539 = 'bx;

assign ashr_ln595_fu_836_p2 = $signed(man_V_2_fu_718_p3) >>> zext_ln595_fu_832_p1;

assign exp_tmp_fu_682_p4 = {{ireg_fu_666_p1[62:52]}};

assign icmp_ln492_fu_576_p2 = ((ap_sig_allocacmp_indvar_flatten7_load == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln493_fu_600_p2 = ((ap_sig_allocacmp_j_load == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln580_fu_726_p2 = ((trunc_ln564_fu_670_p1 == 63'd0) ? 1'b1 : 1'b0);

assign icmp_ln590_fu_738_p2 = (($signed(F2_fu_732_p2) > $signed(12'd8)) ? 1'b1 : 1'b0);

assign icmp_ln591_fu_768_p2 = ((F2_fu_732_p2 == 12'd8) ? 1'b1 : 1'b0);

assign icmp_ln594_fu_805_p2 = ((sh_amt_fu_756_p3 < 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln612_fu_788_p2 = ((tmp_fu_778_p4 == 8'd0) ? 1'b1 : 1'b0);

assign ireg_fu_666_p1 = H_rvd_q0;

assign man_V_1_fu_712_p2 = (54'd0 - zext_ln578_fu_708_p1);

assign man_V_2_fu_718_p3 = ((p_Result_s_fu_674_p3[0:0] == 1'b1) ? man_V_1_fu_712_p2 : zext_ln578_fu_708_p1);

assign p_Result_1_fu_700_p3 = {{1'd1}, {trunc_ln574_fu_696_p1}};

assign p_Result_s_fu_674_p3 = ireg_fu_666_p1[32'd63];

assign select_ln492_1_fu_614_p3 = ((icmp_ln493_fu_600_p2[0:0] == 1'b1) ? add_ln492_fu_594_p2 : ap_sig_allocacmp_i_load);

assign select_ln492_fu_606_p3 = ((icmp_ln493_fu_600_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_j_load);

assign select_ln597_fu_819_p3 = ((tmp_1_fu_811_p3[0:0] == 1'b1) ? 16'd65535 : 16'd0);

assign sext_ln590_fu_764_p1 = sh_amt_fu_756_p3;

assign sext_ln590cast_fu_794_p1 = sext_ln590_fu_764_p1[15:0];

assign sh_amt_fu_756_p3 = ((icmp_ln590_fu_738_p2[0:0] == 1'b1) ? add_ln590_fu_744_p2 : sub_ln590_fu_750_p2);

assign shl_ln613_fu_798_p2 = trunc_ln611_fu_774_p1 << sext_ln590cast_fu_794_p1;

assign sub_ln590_fu_750_p2 = (12'd8 - F2_fu_732_p2);

assign tmp_1_fu_811_p3 = ireg_fu_666_p1[32'd63];

assign tmp_2_fu_630_p4 = {{{select_ln492_1_fu_614_p3}, {trunc_ln494_fu_626_p1}}, {1'd0}};

assign tmp_fu_778_p4 = {{sh_amt_fu_756_p3[11:4]}};

assign trunc_ln492_fu_622_p1 = select_ln492_1_fu_614_p3[2:0];

assign trunc_ln494_fu_626_p1 = select_ln492_fu_606_p3[1:0];

assign trunc_ln564_fu_670_p1 = ireg_fu_666_p1[62:0];

assign trunc_ln574_fu_696_p1 = ireg_fu_666_p1[51:0];

assign trunc_ln592_fu_847_p1 = man_V_2_fu_718_p3[15:0];

assign trunc_ln595_1_fu_842_p1 = ashr_ln595_fu_836_p2[15:0];

assign trunc_ln595_fu_828_p1 = sh_amt_fu_756_p3[5:0];

assign trunc_ln611_fu_774_p1 = man_V_2_fu_718_p3[15:0];

assign zext_ln494_fu_640_p1 = tmp_2_fu_630_p4;

assign zext_ln501_fu_692_p1 = exp_tmp_fu_682_p4;

assign zext_ln578_fu_708_p1 = p_Result_1_fu_700_p3;

assign zext_ln595_fu_832_p1 = trunc_ln595_fu_828_p1;

endmodule //TOP_TOP_Pipeline_VITIS_LOOP_492_5_VITIS_LOOP_493_6
