set SynModuleInfo {
  {SRCNAME TOP_Pipeline_VITIS_LOOP_461_1 MODELNAME TOP_Pipeline_VITIS_LOOP_461_1 RTLNAME TOP_TOP_Pipeline_VITIS_LOOP_461_1
    SUBMODULES {
      {MODELNAME TOP_mux_42_64_1_1 RTLNAME TOP_mux_42_64_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME TOP_flow_control_loop_pipe_sequential_init RTLNAME TOP_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME TOP_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME seedInitialization_Pipeline_SEED_INIT_LOOP MODELNAME seedInitialization_Pipeline_SEED_INIT_LOOP RTLNAME TOP_seedInitialization_Pipeline_SEED_INIT_LOOP
    SUBMODULES {
      {MODELNAME TOP_mul_32s_32ns_32_1_1 RTLNAME TOP_mul_32s_32ns_32_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME seedInitialization MODELNAME seedInitialization RTLNAME TOP_seedInitialization}
  {SRCNAME Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2 MODELNAME Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2 RTLNAME TOP_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2
    SUBMODULES {
      {MODELNAME TOP_dcmp_64ns_64ns_1_1_no_dsp_1 RTLNAME TOP_dcmp_64ns_64ns_1_1_no_dsp_1 BINDTYPE op TYPE dcmp IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4 MODELNAME Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4 RTLNAME TOP_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4}
  {SRCNAME Rayleigh_Pipeline_VITIS_LOOP_67_6 MODELNAME Rayleigh_Pipeline_VITIS_LOOP_67_6 RTLNAME TOP_Rayleigh_Pipeline_VITIS_LOOP_67_6
    SUBMODULES {
      {MODELNAME TOP_dadd_64ns_64ns_64_2_full_dsp_1 RTLNAME TOP_dadd_64ns_64ns_64_2_full_dsp_1 BINDTYPE op TYPE dadd IMPL fulldsp LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME TOP_dmul_64ns_64ns_64_3_max_dsp_1 RTLNAME TOP_dmul_64ns_64ns_64_3_max_dsp_1 BINDTYPE op TYPE dmul IMPL maxdsp LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME Rayleigh MODELNAME Rayleigh RTLNAME TOP_Rayleigh
    SUBMODULES {
      {MODELNAME TOP_Rayleigh_rngMT19937ICN_uniformRNG_mt_odd_0_V_RAM_AUTO_1R1W RTLNAME TOP_Rayleigh_rngMT19937ICN_uniformRNG_mt_odd_0_V_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME TOP_Rayleigh_rngMT19937ICN_1_RAM_AUTO_0R0W RTLNAME TOP_Rayleigh_rngMT19937ICN_1_RAM_AUTO_0R0W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME TOP_Rayleigh_Hr_RAM_AUTO_1R1W RTLNAME TOP_Rayleigh_Hr_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME AWGN MODELNAME AWGN RTLNAME TOP_AWGN
    SUBMODULES {
      {MODELNAME TOP_AWGN_rngMT19937ICN_uniformRNG_mt_odd_0_V_RAM_AUTO_1R1W RTLNAME TOP_AWGN_rngMT19937ICN_uniformRNG_mt_odd_0_V_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME TOP_AWGN_rngMT19937ICN_1_RAM_AUTO_0R0W RTLNAME TOP_AWGN_rngMT19937ICN_1_RAM_AUTO_0R0W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME TOP_Pipeline_VITIS_LOOP_482_2_VITIS_LOOP_483_3 MODELNAME TOP_Pipeline_VITIS_LOOP_482_2_VITIS_LOOP_483_3 RTLNAME TOP_TOP_Pipeline_VITIS_LOOP_482_2_VITIS_LOOP_483_3}
  {SRCNAME TOP_Pipeline_VITIS_LOOP_488_4 MODELNAME TOP_Pipeline_VITIS_LOOP_488_4 RTLNAME TOP_TOP_Pipeline_VITIS_LOOP_488_4}
  {SRCNAME TOP_Pipeline_VITIS_LOOP_492_5_VITIS_LOOP_493_6 MODELNAME TOP_Pipeline_VITIS_LOOP_492_5_VITIS_LOOP_493_6 RTLNAME TOP_TOP_Pipeline_VITIS_LOOP_492_5_VITIS_LOOP_493_6}
  {SRCNAME CORDIC_V_Pipeline_VITIS_LOOP_94_2 MODELNAME CORDIC_V_Pipeline_VITIS_LOOP_94_2 RTLNAME TOP_CORDIC_V_Pipeline_VITIS_LOOP_94_2}
  {SRCNAME CORDIC_V MODELNAME CORDIC_V RTLNAME TOP_CORDIC_V
    SUBMODULES {
      {MODELNAME TOP_mul_mul_16s_8ns_25_4_1 RTLNAME TOP_mul_mul_16s_8ns_25_4_1 BINDTYPE op TYPE mul IMPL dsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME TOP_CORDIC_V_cordic_phase_V_ROM_AUTO_1R RTLNAME TOP_CORDIC_V_cordic_phase_V_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME CORDIC_R_Pipeline_VITIS_LOOP_32_2 MODELNAME CORDIC_R_Pipeline_VITIS_LOOP_32_2 RTLNAME TOP_CORDIC_R_Pipeline_VITIS_LOOP_32_2}
  {SRCNAME CORDIC_R MODELNAME CORDIC_R RTLNAME TOP_CORDIC_R}
  {SRCNAME QRD_Pipeline_LOOP_01 MODELNAME QRD_Pipeline_LOOP_01 RTLNAME TOP_QRD_Pipeline_LOOP_01
    SUBMODULES {
      {MODELNAME TOP_mux_42_16_1_1 RTLNAME TOP_mux_42_16_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME QRD_Pipeline_LOOP_02_VITIS_LOOP_251_6 MODELNAME QRD_Pipeline_LOOP_02_VITIS_LOOP_251_6 RTLNAME TOP_QRD_Pipeline_LOOP_02_VITIS_LOOP_251_6
    SUBMODULES {
      {MODELNAME TOP_mux_84_16_1_1 RTLNAME TOP_mux_84_16_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME QRD_Pipeline_VITIS_LOOP_268_8 MODELNAME QRD_Pipeline_VITIS_LOOP_268_8 RTLNAME TOP_QRD_Pipeline_VITIS_LOOP_268_8
    SUBMODULES {
      {MODELNAME TOP_mux_83_16_1_1 RTLNAME TOP_mux_83_16_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME TOP_mux_864_16_1_1 RTLNAME TOP_mux_864_16_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME TOP_sdiv_24ns_16s_16_28_1 RTLNAME TOP_sdiv_24ns_16s_16_28_1 BINDTYPE op TYPE sdiv IMPL auto LATENCY 27 ALLOW_PRAGMA 1}
      {MODELNAME TOP_mac_mulsub_16s_16s_24ns_24_4_1 RTLNAME TOP_mac_mulsub_16s_16s_24ns_24_4_1 BINDTYPE op TYPE sub IMPL dsp LATENCY 3 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME QRD_Pipeline_VITIS_LOOP_316_9_VITIS_LOOP_317_10 MODELNAME QRD_Pipeline_VITIS_LOOP_316_9_VITIS_LOOP_317_10 RTLNAME TOP_QRD_Pipeline_VITIS_LOOP_316_9_VITIS_LOOP_317_10
    SUBMODULES {
      {MODELNAME TOP_mul_mul_16s_16s_24_4_1 RTLNAME TOP_mul_mul_16s_16s_24_4_1 BINDTYPE op TYPE add IMPL dsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME TOP_mac_muladd_16s_16s_24ns_24_4_1 RTLNAME TOP_mac_muladd_16s_16s_24ns_24_4_1 BINDTYPE op TYPE add IMPL dsp LATENCY 3 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME QRD MODELNAME QRD RTLNAME TOP_QRD
    SUBMODULES {
      {MODELNAME TOP_mux_74_16_1_1 RTLNAME TOP_mux_74_16_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME TOP_Pipeline_VITIS_LOOP_433_1 MODELNAME TOP_Pipeline_VITIS_LOOP_433_1 RTLNAME TOP_TOP_Pipeline_VITIS_LOOP_433_1}
  {SRCNAME KBEST_Pipeline_1 MODELNAME KBEST_Pipeline_1 RTLNAME TOP_KBEST_Pipeline_1}
  {SRCNAME KBEST_Pipeline_VITIS_LOOP_347_1 MODELNAME KBEST_Pipeline_VITIS_LOOP_347_1 RTLNAME TOP_KBEST_Pipeline_VITIS_LOOP_347_1
    SUBMODULES {
      {MODELNAME TOP_mul_mul_16s_9ns_24_4_1 RTLNAME TOP_mul_mul_16s_9ns_24_4_1 BINDTYPE op TYPE mul IMPL dsp LATENCY 3 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME KBEST_Pipeline_VITIS_LOOP_364_3 MODELNAME KBEST_Pipeline_VITIS_LOOP_364_3 RTLNAME TOP_KBEST_Pipeline_VITIS_LOOP_364_3}
  {SRCNAME KBEST_Pipeline_VITIS_LOOP_373_5 MODELNAME KBEST_Pipeline_VITIS_LOOP_373_5 RTLNAME TOP_KBEST_Pipeline_VITIS_LOOP_373_5
    SUBMODULES {
      {MODELNAME TOP_mux_864_32_1_1 RTLNAME TOP_mux_864_32_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME TOP_mux_42_32_1_1 RTLNAME TOP_mux_42_32_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME KBEST_Pipeline_VITIS_LOOP_391_6_VITIS_LOOP_392_7 MODELNAME KBEST_Pipeline_VITIS_LOOP_391_6_VITIS_LOOP_392_7 RTLNAME TOP_KBEST_Pipeline_VITIS_LOOP_391_6_VITIS_LOOP_392_7
    SUBMODULES {
      {MODELNAME TOP_mux_32_32_1_1 RTLNAME TOP_mux_32_32_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME KBEST_Pipeline_VITIS_LOOP_410_9 MODELNAME KBEST_Pipeline_VITIS_LOOP_410_9 RTLNAME TOP_KBEST_Pipeline_VITIS_LOOP_410_9
    SUBMODULES {
      {MODELNAME TOP_mux_84_32_1_1 RTLNAME TOP_mux_84_32_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME KBEST_Pipeline_VITIS_LOOP_420_10 MODELNAME KBEST_Pipeline_VITIS_LOOP_420_10 RTLNAME TOP_KBEST_Pipeline_VITIS_LOOP_420_10}
  {SRCNAME KBEST MODELNAME KBEST RTLNAME TOP_KBEST
    SUBMODULES {
      {MODELNAME TOP_am_submul_16s_16s_24_4_1 RTLNAME TOP_am_submul_16s_16s_24_4_1 BINDTYPE op TYPE mul IMPL dsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME TOP_KBEST_yy_V_RAM_AUTO_1R1W RTLNAME TOP_KBEST_yy_V_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME TOP_KBEST_survival_path_RAM_AUTO_1R1W RTLNAME TOP_KBEST_survival_path_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME TOP MODELNAME TOP RTLNAME TOP IS_TOP 1
    SUBMODULES {
      {MODELNAME TOP_dadddsub_64ns_64ns_64_2_no_dsp_1 RTLNAME TOP_dadddsub_64ns_64ns_64_2_no_dsp_1 BINDTYPE op TYPE dadd IMPL fabric LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME TOP_dadddsub_64ns_64ns_64_2_no_dsp_1 RTLNAME TOP_dadddsub_64ns_64ns_64_2_no_dsp_1 BINDTYPE op TYPE dsub IMPL fabric LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME TOP_dadd_64ns_64ns_64_2_no_dsp_1 RTLNAME TOP_dadd_64ns_64ns_64_2_no_dsp_1 BINDTYPE op TYPE dadd IMPL fabric LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME TOP_dmul_64ns_64ns_64_2_med_dsp_1 RTLNAME TOP_dmul_64ns_64ns_64_2_med_dsp_1 BINDTYPE op TYPE dmul IMPL meddsp LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME TOP_ddiv_64ns_64ns_64_8_no_dsp_1 RTLNAME TOP_ddiv_64ns_64ns_64_8_no_dsp_1 BINDTYPE op TYPE ddiv IMPL fabric LATENCY 7 ALLOW_PRAGMA 1}
      {MODELNAME TOP_dsqrt_64ns_64ns_64_7_no_dsp_1 RTLNAME TOP_dsqrt_64ns_64ns_64_7_no_dsp_1 BINDTYPE op TYPE dsqrt IMPL fabric LATENCY 6 ALLOW_PRAGMA 1}
      {MODELNAME TOP_dlog_64ns_64ns_64_6_med_dsp_1 RTLNAME TOP_dlog_64ns_64ns_64_6_med_dsp_1 BINDTYPE op TYPE dlog IMPL meddsp LATENCY 5 ALLOW_PRAGMA 1}
      {MODELNAME TOP_H_mul_x_RAM_AUTO_1R1W RTLNAME TOP_H_mul_x_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME TOP_H_rvd_RAM_AUTO_1R1W RTLNAME TOP_H_rvd_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME TOP_y_receive_V_RAM_AUTO_1R1W RTLNAME TOP_y_receive_V_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME TOP_Q_RAM_1WNR_AUTO_1R1W RTLNAME TOP_Q_RAM_1WNR_AUTO_1R1W BINDTYPE storage TYPE ram_1wnr IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME TOP_R_V_RAM_AUTO_1R1W RTLNAME TOP_R_V_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
}
