// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module TOP_Rayleigh (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        H_rvd_address0,
        H_rvd_ce0,
        H_rvd_we0,
        H_rvd_d0,
        H_rvd_q0,
        H_rvd_address1,
        H_rvd_ce1,
        H_rvd_we1,
        H_rvd_d1,
        H_rvd_q1,
        H_mul_x_address0,
        H_mul_x_ce0,
        H_mul_x_we0,
        H_mul_x_d0,
        grp_fu_965_p_din0,
        grp_fu_965_p_din1,
        grp_fu_965_p_opcode,
        grp_fu_965_p_dout0,
        grp_fu_965_p_ce,
        grp_fu_969_p_din0,
        grp_fu_969_p_din1,
        grp_fu_969_p_opcode,
        grp_fu_969_p_dout0,
        grp_fu_969_p_ce,
        grp_fu_973_p_din0,
        grp_fu_973_p_din1,
        grp_fu_973_p_opcode,
        grp_fu_973_p_dout0,
        grp_fu_973_p_ce,
        grp_fu_977_p_din0,
        grp_fu_977_p_din1,
        grp_fu_977_p_opcode,
        grp_fu_977_p_dout0,
        grp_fu_977_p_ce,
        grp_fu_981_p_din0,
        grp_fu_981_p_din1,
        grp_fu_981_p_opcode,
        grp_fu_981_p_dout0,
        grp_fu_981_p_ce,
        grp_fu_985_p_din0,
        grp_fu_985_p_din1,
        grp_fu_985_p_opcode,
        grp_fu_985_p_dout0,
        grp_fu_985_p_ce,
        grp_fu_989_p_din0,
        grp_fu_989_p_din1,
        grp_fu_989_p_opcode,
        grp_fu_989_p_dout0,
        grp_fu_989_p_ce,
        grp_fu_993_p_din0,
        grp_fu_993_p_din1,
        grp_fu_993_p_opcode,
        grp_fu_993_p_dout0,
        grp_fu_993_p_ce,
        grp_fu_997_p_din0,
        grp_fu_997_p_din1,
        grp_fu_997_p_opcode,
        grp_fu_997_p_dout0,
        grp_fu_997_p_ce,
        grp_fu_1001_p_din0,
        grp_fu_1001_p_din1,
        grp_fu_1001_p_opcode,
        grp_fu_1001_p_dout0,
        grp_fu_1001_p_ce,
        grp_fu_1005_p_din0,
        grp_fu_1005_p_din1,
        grp_fu_1005_p_opcode,
        grp_fu_1005_p_dout0,
        grp_fu_1005_p_ce,
        grp_fu_1009_p_din0,
        grp_fu_1009_p_din1,
        grp_fu_1009_p_opcode,
        grp_fu_1009_p_dout0,
        grp_fu_1009_p_ce,
        grp_fu_1013_p_din0,
        grp_fu_1013_p_din1,
        grp_fu_1013_p_dout0,
        grp_fu_1013_p_ce,
        grp_fu_1017_p_din0,
        grp_fu_1017_p_din1,
        grp_fu_1017_p_dout0,
        grp_fu_1017_p_ce,
        grp_fu_1021_p_din0,
        grp_fu_1021_p_din1,
        grp_fu_1021_p_dout0,
        grp_fu_1021_p_ce,
        grp_fu_1025_p_din0,
        grp_fu_1025_p_din1,
        grp_fu_1025_p_dout0,
        grp_fu_1025_p_ce,
        grp_fu_1029_p_din0,
        grp_fu_1029_p_din1,
        grp_fu_1029_p_dout0,
        grp_fu_1029_p_ce,
        grp_fu_1033_p_din0,
        grp_fu_1033_p_din1,
        grp_fu_1033_p_dout0,
        grp_fu_1033_p_ce,
        grp_fu_1037_p_din0,
        grp_fu_1037_p_din1,
        grp_fu_1037_p_dout0,
        grp_fu_1037_p_ce,
        grp_fu_1041_p_din0,
        grp_fu_1041_p_din1,
        grp_fu_1041_p_dout0,
        grp_fu_1041_p_ce,
        grp_fu_1045_p_din0,
        grp_fu_1045_p_din1,
        grp_fu_1045_p_dout0,
        grp_fu_1045_p_ce,
        grp_fu_1049_p_din0,
        grp_fu_1049_p_din1,
        grp_fu_1049_p_dout0,
        grp_fu_1049_p_ce,
        grp_fu_1053_p_din0,
        grp_fu_1053_p_din1,
        grp_fu_1053_p_dout0,
        grp_fu_1053_p_ce,
        grp_fu_1057_p_din0,
        grp_fu_1057_p_din1,
        grp_fu_1057_p_dout0,
        grp_fu_1057_p_ce,
        grp_fu_1061_p_din0,
        grp_fu_1061_p_din1,
        grp_fu_1061_p_dout0,
        grp_fu_1061_p_ce,
        grp_fu_1065_p_din0,
        grp_fu_1065_p_din1,
        grp_fu_1065_p_dout0,
        grp_fu_1065_p_ce,
        grp_fu_1069_p_din0,
        grp_fu_1069_p_din1,
        grp_fu_1069_p_dout0,
        grp_fu_1069_p_ce,
        grp_fu_1073_p_din0,
        grp_fu_1073_p_din1,
        grp_fu_1073_p_dout0,
        grp_fu_1073_p_ce,
        grp_fu_1077_p_din0,
        grp_fu_1077_p_din1,
        grp_fu_1077_p_dout0,
        grp_fu_1077_p_ce,
        grp_fu_1081_p_din0,
        grp_fu_1081_p_din1,
        grp_fu_1081_p_opcode,
        grp_fu_1081_p_dout0,
        grp_fu_1081_p_ce
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] H_rvd_address0;
output   H_rvd_ce0;
output   H_rvd_we0;
output  [63:0] H_rvd_d0;
input  [63:0] H_rvd_q0;
output  [5:0] H_rvd_address1;
output   H_rvd_ce1;
output   H_rvd_we1;
output  [63:0] H_rvd_d1;
input  [63:0] H_rvd_q1;
output  [2:0] H_mul_x_address0;
output   H_mul_x_ce0;
output   H_mul_x_we0;
output  [63:0] H_mul_x_d0;
output  [63:0] grp_fu_965_p_din0;
output  [63:0] grp_fu_965_p_din1;
output  [0:0] grp_fu_965_p_opcode;
input  [63:0] grp_fu_965_p_dout0;
output   grp_fu_965_p_ce;
output  [63:0] grp_fu_969_p_din0;
output  [63:0] grp_fu_969_p_din1;
output  [0:0] grp_fu_969_p_opcode;
input  [63:0] grp_fu_969_p_dout0;
output   grp_fu_969_p_ce;
output  [63:0] grp_fu_973_p_din0;
output  [63:0] grp_fu_973_p_din1;
output  [1:0] grp_fu_973_p_opcode;
input  [63:0] grp_fu_973_p_dout0;
output   grp_fu_973_p_ce;
output  [63:0] grp_fu_977_p_din0;
output  [63:0] grp_fu_977_p_din1;
output  [1:0] grp_fu_977_p_opcode;
input  [63:0] grp_fu_977_p_dout0;
output   grp_fu_977_p_ce;
output  [63:0] grp_fu_981_p_din0;
output  [63:0] grp_fu_981_p_din1;
output  [1:0] grp_fu_981_p_opcode;
input  [63:0] grp_fu_981_p_dout0;
output   grp_fu_981_p_ce;
output  [63:0] grp_fu_985_p_din0;
output  [63:0] grp_fu_985_p_din1;
output  [1:0] grp_fu_985_p_opcode;
input  [63:0] grp_fu_985_p_dout0;
output   grp_fu_985_p_ce;
output  [63:0] grp_fu_989_p_din0;
output  [63:0] grp_fu_989_p_din1;
output  [1:0] grp_fu_989_p_opcode;
input  [63:0] grp_fu_989_p_dout0;
output   grp_fu_989_p_ce;
output  [63:0] grp_fu_993_p_din0;
output  [63:0] grp_fu_993_p_din1;
output  [1:0] grp_fu_993_p_opcode;
input  [63:0] grp_fu_993_p_dout0;
output   grp_fu_993_p_ce;
output  [63:0] grp_fu_997_p_din0;
output  [63:0] grp_fu_997_p_din1;
output  [1:0] grp_fu_997_p_opcode;
input  [63:0] grp_fu_997_p_dout0;
output   grp_fu_997_p_ce;
output  [63:0] grp_fu_1001_p_din0;
output  [63:0] grp_fu_1001_p_din1;
output  [1:0] grp_fu_1001_p_opcode;
input  [63:0] grp_fu_1001_p_dout0;
output   grp_fu_1001_p_ce;
output  [63:0] grp_fu_1005_p_din0;
output  [63:0] grp_fu_1005_p_din1;
output  [1:0] grp_fu_1005_p_opcode;
input  [63:0] grp_fu_1005_p_dout0;
output   grp_fu_1005_p_ce;
output  [63:0] grp_fu_1009_p_din0;
output  [63:0] grp_fu_1009_p_din1;
output  [1:0] grp_fu_1009_p_opcode;
input  [63:0] grp_fu_1009_p_dout0;
output   grp_fu_1009_p_ce;
output  [63:0] grp_fu_1013_p_din0;
output  [63:0] grp_fu_1013_p_din1;
input  [63:0] grp_fu_1013_p_dout0;
output   grp_fu_1013_p_ce;
output  [63:0] grp_fu_1017_p_din0;
output  [63:0] grp_fu_1017_p_din1;
input  [63:0] grp_fu_1017_p_dout0;
output   grp_fu_1017_p_ce;
output  [63:0] grp_fu_1021_p_din0;
output  [63:0] grp_fu_1021_p_din1;
input  [63:0] grp_fu_1021_p_dout0;
output   grp_fu_1021_p_ce;
output  [63:0] grp_fu_1025_p_din0;
output  [63:0] grp_fu_1025_p_din1;
input  [63:0] grp_fu_1025_p_dout0;
output   grp_fu_1025_p_ce;
output  [63:0] grp_fu_1029_p_din0;
output  [63:0] grp_fu_1029_p_din1;
input  [63:0] grp_fu_1029_p_dout0;
output   grp_fu_1029_p_ce;
output  [63:0] grp_fu_1033_p_din0;
output  [63:0] grp_fu_1033_p_din1;
input  [63:0] grp_fu_1033_p_dout0;
output   grp_fu_1033_p_ce;
output  [63:0] grp_fu_1037_p_din0;
output  [63:0] grp_fu_1037_p_din1;
input  [63:0] grp_fu_1037_p_dout0;
output   grp_fu_1037_p_ce;
output  [63:0] grp_fu_1041_p_din0;
output  [63:0] grp_fu_1041_p_din1;
input  [63:0] grp_fu_1041_p_dout0;
output   grp_fu_1041_p_ce;
output  [63:0] grp_fu_1045_p_din0;
output  [63:0] grp_fu_1045_p_din1;
input  [63:0] grp_fu_1045_p_dout0;
output   grp_fu_1045_p_ce;
output  [63:0] grp_fu_1049_p_din0;
output  [63:0] grp_fu_1049_p_din1;
input  [63:0] grp_fu_1049_p_dout0;
output   grp_fu_1049_p_ce;
output  [63:0] grp_fu_1053_p_din0;
output  [63:0] grp_fu_1053_p_din1;
input  [63:0] grp_fu_1053_p_dout0;
output   grp_fu_1053_p_ce;
output  [63:0] grp_fu_1057_p_din0;
output  [63:0] grp_fu_1057_p_din1;
input  [63:0] grp_fu_1057_p_dout0;
output   grp_fu_1057_p_ce;
output  [63:0] grp_fu_1061_p_din0;
output  [63:0] grp_fu_1061_p_din1;
input  [63:0] grp_fu_1061_p_dout0;
output   grp_fu_1061_p_ce;
output  [63:0] grp_fu_1065_p_din0;
output  [63:0] grp_fu_1065_p_din1;
input  [63:0] grp_fu_1065_p_dout0;
output   grp_fu_1065_p_ce;
output  [63:0] grp_fu_1069_p_din0;
output  [63:0] grp_fu_1069_p_din1;
input  [63:0] grp_fu_1069_p_dout0;
output   grp_fu_1069_p_ce;
output  [63:0] grp_fu_1073_p_din0;
output  [63:0] grp_fu_1073_p_din1;
input  [63:0] grp_fu_1073_p_dout0;
output   grp_fu_1073_p_ce;
output  [63:0] grp_fu_1077_p_din0;
output  [63:0] grp_fu_1077_p_din1;
input  [63:0] grp_fu_1077_p_dout0;
output   grp_fu_1077_p_ce;
output  [63:0] grp_fu_1081_p_din0;
output  [63:0] grp_fu_1081_p_din1;
output  [1:0] grp_fu_1081_p_opcode;
input  [63:0] grp_fu_1081_p_dout0;
output   grp_fu_1081_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[5:0] H_rvd_address0;
reg H_rvd_ce0;
reg H_rvd_we0;
reg[5:0] H_rvd_address1;
reg H_rvd_ce1;
reg H_rvd_we1;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] rngMT19937ICN_uniformRNG_x_k_p_0_V_reg_98;
wire    ap_CS_fsm_state2;
reg   [31:0] rngMT19937ICN_uniformRNG_x_k_p_1_V_reg_103;
reg   [31:0] rngMT19937ICN_uniformRNG_x_k_p_2_V_reg_108;
reg   [31:0] rngMT19937ICN_uniformRNG_x_k_p_m_V_reg_113;
reg   [8:0] rngMT19937ICN_uniformRNG_mt_odd_0_V_address0;
reg    rngMT19937ICN_uniformRNG_mt_odd_0_V_ce0;
reg    rngMT19937ICN_uniformRNG_mt_odd_0_V_we0;
reg   [31:0] rngMT19937ICN_uniformRNG_mt_odd_0_V_d0;
wire   [31:0] rngMT19937ICN_uniformRNG_mt_odd_0_V_q0;
reg   [8:0] rngMT19937ICN_uniformRNG_mt_odd_0_V_address1;
reg    rngMT19937ICN_uniformRNG_mt_odd_0_V_ce1;
wire   [31:0] rngMT19937ICN_uniformRNG_mt_odd_0_V_q1;
reg   [8:0] rngMT19937ICN_uniformRNG_mt_even_0_V_address0;
reg    rngMT19937ICN_uniformRNG_mt_even_0_V_ce0;
reg    rngMT19937ICN_uniformRNG_mt_even_0_V_we0;
reg   [31:0] rngMT19937ICN_uniformRNG_mt_even_0_V_d0;
wire   [31:0] rngMT19937ICN_uniformRNG_mt_even_0_V_q0;
reg    rngMT19937ICN_uniformRNG_mt_even_0_V_ce1;
wire   [31:0] rngMT19937ICN_uniformRNG_mt_even_0_V_q1;
reg   [3:0] Hr_address0;
reg    Hr_ce0;
reg    Hr_we0;
wire   [63:0] Hr_q0;
reg   [3:0] Hi_address0;
reg    Hi_ce0;
reg    Hi_we0;
wire   [63:0] Hi_q0;
wire    grp_seedInitialization_fu_40_ap_start;
wire    grp_seedInitialization_fu_40_ap_done;
wire    grp_seedInitialization_fu_40_ap_idle;
wire    grp_seedInitialization_fu_40_ap_ready;
wire   [8:0] grp_seedInitialization_fu_40_this_mt_odd_0_address0;
wire    grp_seedInitialization_fu_40_this_mt_odd_0_ce0;
wire    grp_seedInitialization_fu_40_this_mt_odd_0_we0;
wire   [31:0] grp_seedInitialization_fu_40_this_mt_odd_0_d0;
wire   [8:0] grp_seedInitialization_fu_40_this_mt_odd_0_address1;
wire    grp_seedInitialization_fu_40_this_mt_odd_0_ce1;
wire   [8:0] grp_seedInitialization_fu_40_this_mt_odd_1_address0;
wire    grp_seedInitialization_fu_40_this_mt_odd_1_ce0;
wire    grp_seedInitialization_fu_40_this_mt_odd_1_we0;
wire   [31:0] grp_seedInitialization_fu_40_this_mt_odd_1_d0;
wire   [8:0] grp_seedInitialization_fu_40_this_mt_even_0_address0;
wire    grp_seedInitialization_fu_40_this_mt_even_0_ce0;
wire    grp_seedInitialization_fu_40_this_mt_even_0_we0;
wire   [31:0] grp_seedInitialization_fu_40_this_mt_even_0_d0;
wire   [8:0] grp_seedInitialization_fu_40_this_mt_even_1_address0;
wire    grp_seedInitialization_fu_40_this_mt_even_1_ce0;
wire    grp_seedInitialization_fu_40_this_mt_even_1_we0;
wire   [31:0] grp_seedInitialization_fu_40_this_mt_even_1_d0;
wire   [31:0] grp_seedInitialization_fu_40_ap_return_0;
wire   [31:0] grp_seedInitialization_fu_40_ap_return_1;
wire   [31:0] grp_seedInitialization_fu_40_ap_return_2;
wire   [31:0] grp_seedInitialization_fu_40_ap_return_3;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_ap_start;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_ap_done;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_ap_idle;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_ap_ready;
wire   [3:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_Hr_address0;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_Hr_ce0;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_Hr_we0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_Hr_d0;
wire   [3:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_Hi_address0;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_Hi_ce0;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_Hi_we0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_Hi_d0;
wire   [8:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_even_0_V_address0;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_even_0_V_ce0;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_even_0_V_we0;
wire   [31:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_even_0_V_d0;
wire   [8:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_even_0_V_address1;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_even_0_V_ce1;
wire   [8:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_odd_0_V_address0;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_odd_0_V_ce0;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_odd_0_V_we0;
wire   [31:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_odd_0_V_d0;
wire   [8:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_odd_0_V_address1;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_odd_0_V_ce1;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_118_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_118_p_din1;
wire   [0:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_118_p_opcode;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_118_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_122_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_122_p_din1;
wire   [0:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_122_p_opcode;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_122_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_126_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_126_p_din1;
wire   [1:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_126_p_opcode;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_126_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_130_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_130_p_din1;
wire   [1:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_130_p_opcode;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_130_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_134_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_134_p_din1;
wire   [1:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_134_p_opcode;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_134_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_138_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_138_p_din1;
wire   [1:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_138_p_opcode;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_138_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_142_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_142_p_din1;
wire   [1:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_142_p_opcode;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_142_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_146_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_146_p_din1;
wire   [1:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_146_p_opcode;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_146_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_150_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_150_p_din1;
wire   [1:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_150_p_opcode;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_150_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_154_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_154_p_din1;
wire   [1:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_154_p_opcode;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_154_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_158_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_158_p_din1;
wire   [1:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_158_p_opcode;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_158_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_162_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_162_p_din1;
wire   [1:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_162_p_opcode;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_162_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_166_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_166_p_din1;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_166_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_170_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_170_p_din1;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_170_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_174_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_174_p_din1;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_174_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_178_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_178_p_din1;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_178_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_182_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_182_p_din1;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_182_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_186_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_186_p_din1;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_186_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_190_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_190_p_din1;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_190_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_194_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_194_p_din1;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_194_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_198_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_198_p_din1;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_198_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_202_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_202_p_din1;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_202_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_206_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_206_p_din1;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_206_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_210_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_210_p_din1;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_210_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_214_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_214_p_din1;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_214_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_218_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_218_p_din1;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_218_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_222_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_222_p_din1;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_222_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_226_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_226_p_din1;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_226_p_ce;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_230_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_230_p_din1;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_230_p_ce;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_ap_start;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_ap_done;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_ap_idle;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_ap_ready;
wire   [3:0] grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_Hr_address0;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_Hr_ce0;
wire   [3:0] grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_Hi_address0;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_Hi_ce0;
wire   [5:0] grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_H_rvd_address0;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_H_rvd_ce0;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_H_rvd_we0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_H_rvd_d0;
wire   [5:0] grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_H_rvd_address1;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_H_rvd_ce1;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_H_rvd_we1;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_H_rvd_d1;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_ap_start;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_ap_done;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_ap_idle;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_ap_ready;
wire   [5:0] grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_H_rvd_address0;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_H_rvd_ce0;
wire   [5:0] grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_H_rvd_address1;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_H_rvd_ce1;
wire   [2:0] grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_H_mul_x_address0;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_H_mul_x_ce0;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_H_mul_x_we0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_H_mul_x_d0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_grp_fu_234_p_din0;
wire   [63:0] grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_grp_fu_234_p_din1;
wire   [1:0] grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_grp_fu_234_p_opcode;
wire    grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_grp_fu_234_p_ce;
reg    grp_seedInitialization_fu_40_ap_start_reg;
reg    grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_ap_start_reg;
reg   [7:0] ap_NS_fsm;
wire    ap_NS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    grp_fu_118_ce;
reg    grp_fu_122_ce;
reg    grp_fu_126_ce;
reg    grp_fu_130_ce;
reg    grp_fu_134_ce;
reg    grp_fu_138_ce;
reg    grp_fu_142_ce;
reg    grp_fu_146_ce;
reg    grp_fu_150_ce;
reg    grp_fu_154_ce;
reg    grp_fu_158_ce;
reg    grp_fu_162_ce;
reg    grp_fu_166_ce;
reg    grp_fu_170_ce;
reg    grp_fu_174_ce;
reg    grp_fu_178_ce;
reg    grp_fu_182_ce;
reg    grp_fu_186_ce;
reg    grp_fu_190_ce;
reg    grp_fu_194_ce;
reg    grp_fu_198_ce;
reg    grp_fu_202_ce;
reg    grp_fu_206_ce;
reg    grp_fu_210_ce;
reg    grp_fu_214_ce;
reg    grp_fu_218_ce;
reg    grp_fu_222_ce;
reg    grp_fu_226_ce;
reg    grp_fu_230_ce;
reg    grp_fu_234_ce;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_seedInitialization_fu_40_ap_start_reg = 1'b0;
#0 grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_ap_start_reg = 1'b0;
#0 grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_ap_start_reg = 1'b0;
#0 grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_ap_start_reg = 1'b0;
end

TOP_Rayleigh_rngMT19937ICN_uniformRNG_mt_odd_0_V_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
rngMT19937ICN_uniformRNG_mt_odd_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(rngMT19937ICN_uniformRNG_mt_odd_0_V_address0),
    .ce0(rngMT19937ICN_uniformRNG_mt_odd_0_V_ce0),
    .we0(rngMT19937ICN_uniformRNG_mt_odd_0_V_we0),
    .d0(rngMT19937ICN_uniformRNG_mt_odd_0_V_d0),
    .q0(rngMT19937ICN_uniformRNG_mt_odd_0_V_q0),
    .address1(rngMT19937ICN_uniformRNG_mt_odd_0_V_address1),
    .ce1(rngMT19937ICN_uniformRNG_mt_odd_0_V_ce1),
    .q1(rngMT19937ICN_uniformRNG_mt_odd_0_V_q1)
);

TOP_Rayleigh_rngMT19937ICN_1_RAM_AUTO_0R0W #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
rngMT19937ICN_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_seedInitialization_fu_40_this_mt_odd_1_address0),
    .ce0(grp_seedInitialization_fu_40_this_mt_odd_1_ce0),
    .we0(grp_seedInitialization_fu_40_this_mt_odd_1_we0),
    .d0(grp_seedInitialization_fu_40_this_mt_odd_1_d0)
);

TOP_Rayleigh_rngMT19937ICN_uniformRNG_mt_odd_0_V_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
rngMT19937ICN_uniformRNG_mt_even_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(rngMT19937ICN_uniformRNG_mt_even_0_V_address0),
    .ce0(rngMT19937ICN_uniformRNG_mt_even_0_V_ce0),
    .we0(rngMT19937ICN_uniformRNG_mt_even_0_V_we0),
    .d0(rngMT19937ICN_uniformRNG_mt_even_0_V_d0),
    .q0(rngMT19937ICN_uniformRNG_mt_even_0_V_q0),
    .address1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_even_0_V_address1),
    .ce1(rngMT19937ICN_uniformRNG_mt_even_0_V_ce1),
    .q1(rngMT19937ICN_uniformRNG_mt_even_0_V_q1)
);

TOP_Rayleigh_rngMT19937ICN_1_RAM_AUTO_0R0W #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
rngMT19937ICN_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_seedInitialization_fu_40_this_mt_even_1_address0),
    .ce0(grp_seedInitialization_fu_40_this_mt_even_1_ce0),
    .we0(grp_seedInitialization_fu_40_this_mt_even_1_we0),
    .d0(grp_seedInitialization_fu_40_this_mt_even_1_d0)
);

TOP_Rayleigh_Hr_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
Hr_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Hr_address0),
    .ce0(Hr_ce0),
    .we0(Hr_we0),
    .d0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_Hr_d0),
    .q0(Hr_q0)
);

TOP_Rayleigh_Hr_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
Hi_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Hi_address0),
    .ce0(Hi_ce0),
    .we0(Hi_we0),
    .d0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_Hi_d0),
    .q0(Hi_q0)
);

TOP_seedInitialization grp_seedInitialization_fu_40(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_seedInitialization_fu_40_ap_start),
    .ap_done(grp_seedInitialization_fu_40_ap_done),
    .ap_idle(grp_seedInitialization_fu_40_ap_idle),
    .ap_ready(grp_seedInitialization_fu_40_ap_ready),
    .this_mt_odd_0_address0(grp_seedInitialization_fu_40_this_mt_odd_0_address0),
    .this_mt_odd_0_ce0(grp_seedInitialization_fu_40_this_mt_odd_0_ce0),
    .this_mt_odd_0_we0(grp_seedInitialization_fu_40_this_mt_odd_0_we0),
    .this_mt_odd_0_d0(grp_seedInitialization_fu_40_this_mt_odd_0_d0),
    .this_mt_odd_0_q0(rngMT19937ICN_uniformRNG_mt_odd_0_V_q0),
    .this_mt_odd_0_address1(grp_seedInitialization_fu_40_this_mt_odd_0_address1),
    .this_mt_odd_0_ce1(grp_seedInitialization_fu_40_this_mt_odd_0_ce1),
    .this_mt_odd_0_q1(rngMT19937ICN_uniformRNG_mt_odd_0_V_q1),
    .this_mt_odd_1_address0(grp_seedInitialization_fu_40_this_mt_odd_1_address0),
    .this_mt_odd_1_ce0(grp_seedInitialization_fu_40_this_mt_odd_1_ce0),
    .this_mt_odd_1_we0(grp_seedInitialization_fu_40_this_mt_odd_1_we0),
    .this_mt_odd_1_d0(grp_seedInitialization_fu_40_this_mt_odd_1_d0),
    .this_mt_even_0_address0(grp_seedInitialization_fu_40_this_mt_even_0_address0),
    .this_mt_even_0_ce0(grp_seedInitialization_fu_40_this_mt_even_0_ce0),
    .this_mt_even_0_we0(grp_seedInitialization_fu_40_this_mt_even_0_we0),
    .this_mt_even_0_d0(grp_seedInitialization_fu_40_this_mt_even_0_d0),
    .this_mt_even_0_q0(rngMT19937ICN_uniformRNG_mt_even_0_V_q0),
    .this_mt_even_1_address0(grp_seedInitialization_fu_40_this_mt_even_1_address0),
    .this_mt_even_1_ce0(grp_seedInitialization_fu_40_this_mt_even_1_ce0),
    .this_mt_even_1_we0(grp_seedInitialization_fu_40_this_mt_even_1_we0),
    .this_mt_even_1_d0(grp_seedInitialization_fu_40_this_mt_even_1_d0),
    .seed(6'd37),
    .ap_return_0(grp_seedInitialization_fu_40_ap_return_0),
    .ap_return_1(grp_seedInitialization_fu_40_ap_return_1),
    .ap_return_2(grp_seedInitialization_fu_40_ap_return_2),
    .ap_return_3(grp_seedInitialization_fu_40_ap_return_3)
);

TOP_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2 grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_ap_start),
    .ap_done(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_ap_done),
    .ap_idle(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_ap_idle),
    .ap_ready(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_ap_ready),
    .rngMT19937ICN_uniformRNG_x_k_p_0_V(rngMT19937ICN_uniformRNG_x_k_p_0_V_reg_98),
    .rngMT19937ICN_uniformRNG_x_k_p_1_V(rngMT19937ICN_uniformRNG_x_k_p_1_V_reg_103),
    .rngMT19937ICN_uniformRNG_x_k_p_m_V(rngMT19937ICN_uniformRNG_x_k_p_m_V_reg_113),
    .rngMT19937ICN_uniformRNG_x_k_p_2_V(rngMT19937ICN_uniformRNG_x_k_p_2_V_reg_108),
    .Hr_address0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_Hr_address0),
    .Hr_ce0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_Hr_ce0),
    .Hr_we0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_Hr_we0),
    .Hr_d0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_Hr_d0),
    .Hi_address0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_Hi_address0),
    .Hi_ce0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_Hi_ce0),
    .Hi_we0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_Hi_we0),
    .Hi_d0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_Hi_d0),
    .rngMT19937ICN_uniformRNG_mt_even_0_V_address0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_even_0_V_address0),
    .rngMT19937ICN_uniformRNG_mt_even_0_V_ce0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_even_0_V_ce0),
    .rngMT19937ICN_uniformRNG_mt_even_0_V_we0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_even_0_V_we0),
    .rngMT19937ICN_uniformRNG_mt_even_0_V_d0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_even_0_V_d0),
    .rngMT19937ICN_uniformRNG_mt_even_0_V_q0(rngMT19937ICN_uniformRNG_mt_even_0_V_q0),
    .rngMT19937ICN_uniformRNG_mt_even_0_V_address1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_even_0_V_address1),
    .rngMT19937ICN_uniformRNG_mt_even_0_V_ce1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_even_0_V_ce1),
    .rngMT19937ICN_uniformRNG_mt_even_0_V_q1(rngMT19937ICN_uniformRNG_mt_even_0_V_q1),
    .rngMT19937ICN_uniformRNG_mt_odd_0_V_address0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_odd_0_V_address0),
    .rngMT19937ICN_uniformRNG_mt_odd_0_V_ce0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_odd_0_V_ce0),
    .rngMT19937ICN_uniformRNG_mt_odd_0_V_we0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_odd_0_V_we0),
    .rngMT19937ICN_uniformRNG_mt_odd_0_V_d0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_odd_0_V_d0),
    .rngMT19937ICN_uniformRNG_mt_odd_0_V_q0(rngMT19937ICN_uniformRNG_mt_odd_0_V_q0),
    .rngMT19937ICN_uniformRNG_mt_odd_0_V_address1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_odd_0_V_address1),
    .rngMT19937ICN_uniformRNG_mt_odd_0_V_ce1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_odd_0_V_ce1),
    .rngMT19937ICN_uniformRNG_mt_odd_0_V_q1(rngMT19937ICN_uniformRNG_mt_odd_0_V_q1),
    .grp_fu_118_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_118_p_din0),
    .grp_fu_118_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_118_p_din1),
    .grp_fu_118_p_opcode(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_118_p_opcode),
    .grp_fu_118_p_dout0(grp_fu_965_p_dout0),
    .grp_fu_118_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_118_p_ce),
    .grp_fu_122_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_122_p_din0),
    .grp_fu_122_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_122_p_din1),
    .grp_fu_122_p_opcode(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_122_p_opcode),
    .grp_fu_122_p_dout0(grp_fu_969_p_dout0),
    .grp_fu_122_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_122_p_ce),
    .grp_fu_126_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_126_p_din0),
    .grp_fu_126_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_126_p_din1),
    .grp_fu_126_p_opcode(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_126_p_opcode),
    .grp_fu_126_p_dout0(grp_fu_973_p_dout0),
    .grp_fu_126_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_126_p_ce),
    .grp_fu_130_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_130_p_din0),
    .grp_fu_130_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_130_p_din1),
    .grp_fu_130_p_opcode(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_130_p_opcode),
    .grp_fu_130_p_dout0(grp_fu_977_p_dout0),
    .grp_fu_130_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_130_p_ce),
    .grp_fu_134_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_134_p_din0),
    .grp_fu_134_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_134_p_din1),
    .grp_fu_134_p_opcode(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_134_p_opcode),
    .grp_fu_134_p_dout0(grp_fu_981_p_dout0),
    .grp_fu_134_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_134_p_ce),
    .grp_fu_138_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_138_p_din0),
    .grp_fu_138_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_138_p_din1),
    .grp_fu_138_p_opcode(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_138_p_opcode),
    .grp_fu_138_p_dout0(grp_fu_985_p_dout0),
    .grp_fu_138_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_138_p_ce),
    .grp_fu_142_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_142_p_din0),
    .grp_fu_142_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_142_p_din1),
    .grp_fu_142_p_opcode(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_142_p_opcode),
    .grp_fu_142_p_dout0(grp_fu_989_p_dout0),
    .grp_fu_142_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_142_p_ce),
    .grp_fu_146_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_146_p_din0),
    .grp_fu_146_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_146_p_din1),
    .grp_fu_146_p_opcode(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_146_p_opcode),
    .grp_fu_146_p_dout0(grp_fu_993_p_dout0),
    .grp_fu_146_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_146_p_ce),
    .grp_fu_150_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_150_p_din0),
    .grp_fu_150_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_150_p_din1),
    .grp_fu_150_p_opcode(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_150_p_opcode),
    .grp_fu_150_p_dout0(grp_fu_997_p_dout0),
    .grp_fu_150_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_150_p_ce),
    .grp_fu_154_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_154_p_din0),
    .grp_fu_154_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_154_p_din1),
    .grp_fu_154_p_opcode(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_154_p_opcode),
    .grp_fu_154_p_dout0(grp_fu_1001_p_dout0),
    .grp_fu_154_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_154_p_ce),
    .grp_fu_158_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_158_p_din0),
    .grp_fu_158_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_158_p_din1),
    .grp_fu_158_p_opcode(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_158_p_opcode),
    .grp_fu_158_p_dout0(grp_fu_1005_p_dout0),
    .grp_fu_158_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_158_p_ce),
    .grp_fu_162_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_162_p_din0),
    .grp_fu_162_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_162_p_din1),
    .grp_fu_162_p_opcode(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_162_p_opcode),
    .grp_fu_162_p_dout0(grp_fu_1009_p_dout0),
    .grp_fu_162_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_162_p_ce),
    .grp_fu_166_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_166_p_din0),
    .grp_fu_166_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_166_p_din1),
    .grp_fu_166_p_dout0(grp_fu_1013_p_dout0),
    .grp_fu_166_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_166_p_ce),
    .grp_fu_170_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_170_p_din0),
    .grp_fu_170_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_170_p_din1),
    .grp_fu_170_p_dout0(grp_fu_1017_p_dout0),
    .grp_fu_170_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_170_p_ce),
    .grp_fu_174_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_174_p_din0),
    .grp_fu_174_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_174_p_din1),
    .grp_fu_174_p_dout0(grp_fu_1021_p_dout0),
    .grp_fu_174_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_174_p_ce),
    .grp_fu_178_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_178_p_din0),
    .grp_fu_178_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_178_p_din1),
    .grp_fu_178_p_dout0(grp_fu_1025_p_dout0),
    .grp_fu_178_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_178_p_ce),
    .grp_fu_182_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_182_p_din0),
    .grp_fu_182_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_182_p_din1),
    .grp_fu_182_p_dout0(grp_fu_1029_p_dout0),
    .grp_fu_182_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_182_p_ce),
    .grp_fu_186_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_186_p_din0),
    .grp_fu_186_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_186_p_din1),
    .grp_fu_186_p_dout0(grp_fu_1033_p_dout0),
    .grp_fu_186_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_186_p_ce),
    .grp_fu_190_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_190_p_din0),
    .grp_fu_190_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_190_p_din1),
    .grp_fu_190_p_dout0(grp_fu_1037_p_dout0),
    .grp_fu_190_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_190_p_ce),
    .grp_fu_194_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_194_p_din0),
    .grp_fu_194_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_194_p_din1),
    .grp_fu_194_p_dout0(grp_fu_1041_p_dout0),
    .grp_fu_194_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_194_p_ce),
    .grp_fu_198_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_198_p_din0),
    .grp_fu_198_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_198_p_din1),
    .grp_fu_198_p_dout0(grp_fu_1045_p_dout0),
    .grp_fu_198_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_198_p_ce),
    .grp_fu_202_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_202_p_din0),
    .grp_fu_202_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_202_p_din1),
    .grp_fu_202_p_dout0(grp_fu_1049_p_dout0),
    .grp_fu_202_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_202_p_ce),
    .grp_fu_206_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_206_p_din0),
    .grp_fu_206_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_206_p_din1),
    .grp_fu_206_p_dout0(grp_fu_1053_p_dout0),
    .grp_fu_206_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_206_p_ce),
    .grp_fu_210_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_210_p_din0),
    .grp_fu_210_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_210_p_din1),
    .grp_fu_210_p_dout0(grp_fu_1057_p_dout0),
    .grp_fu_210_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_210_p_ce),
    .grp_fu_214_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_214_p_din0),
    .grp_fu_214_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_214_p_din1),
    .grp_fu_214_p_dout0(grp_fu_1061_p_dout0),
    .grp_fu_214_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_214_p_ce),
    .grp_fu_218_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_218_p_din0),
    .grp_fu_218_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_218_p_din1),
    .grp_fu_218_p_dout0(grp_fu_1065_p_dout0),
    .grp_fu_218_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_218_p_ce),
    .grp_fu_222_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_222_p_din0),
    .grp_fu_222_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_222_p_din1),
    .grp_fu_222_p_dout0(grp_fu_1069_p_dout0),
    .grp_fu_222_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_222_p_ce),
    .grp_fu_226_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_226_p_din0),
    .grp_fu_226_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_226_p_din1),
    .grp_fu_226_p_dout0(grp_fu_1073_p_dout0),
    .grp_fu_226_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_226_p_ce),
    .grp_fu_230_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_230_p_din0),
    .grp_fu_230_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_230_p_din1),
    .grp_fu_230_p_dout0(grp_fu_1077_p_dout0),
    .grp_fu_230_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_230_p_ce)
);

TOP_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4 grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_ap_start),
    .ap_done(grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_ap_done),
    .ap_idle(grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_ap_idle),
    .ap_ready(grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_ap_ready),
    .Hr_address0(grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_Hr_address0),
    .Hr_ce0(grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_Hr_ce0),
    .Hr_q0(Hr_q0),
    .Hi_address0(grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_Hi_address0),
    .Hi_ce0(grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_Hi_ce0),
    .Hi_q0(Hi_q0),
    .H_rvd_address0(grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_H_rvd_address0),
    .H_rvd_ce0(grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_H_rvd_ce0),
    .H_rvd_we0(grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_H_rvd_we0),
    .H_rvd_d0(grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_H_rvd_d0),
    .H_rvd_address1(grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_H_rvd_address1),
    .H_rvd_ce1(grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_H_rvd_ce1),
    .H_rvd_we1(grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_H_rvd_we1),
    .H_rvd_d1(grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_H_rvd_d1)
);

TOP_Rayleigh_Pipeline_VITIS_LOOP_67_6 grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_ap_start),
    .ap_done(grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_ap_done),
    .ap_idle(grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_ap_idle),
    .ap_ready(grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_ap_ready),
    .H_rvd_address0(grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_H_rvd_address0),
    .H_rvd_ce0(grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_H_rvd_ce0),
    .H_rvd_q0(H_rvd_q0),
    .H_rvd_address1(grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_H_rvd_address1),
    .H_rvd_ce1(grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_H_rvd_ce1),
    .H_rvd_q1(H_rvd_q1),
    .H_mul_x_address0(grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_H_mul_x_address0),
    .H_mul_x_ce0(grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_H_mul_x_ce0),
    .H_mul_x_we0(grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_H_mul_x_we0),
    .H_mul_x_d0(grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_H_mul_x_d0),
    .grp_fu_234_p_din0(grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_grp_fu_234_p_din0),
    .grp_fu_234_p_din1(grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_grp_fu_234_p_din1),
    .grp_fu_234_p_opcode(grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_grp_fu_234_p_opcode),
    .grp_fu_234_p_dout0(grp_fu_1081_p_dout0),
    .grp_fu_234_p_ce(grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_grp_fu_234_p_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (1'b1 == ap_NS_fsm_state3))) begin
            grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_ap_start_reg <= 1'b1;
        end else if ((grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_ap_ready == 1'b1)) begin
            grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_ap_start_reg <= 1'b1;
        end else if ((grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_ap_ready == 1'b1)) begin
            grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_ap_start_reg <= 1'b1;
        end else if ((grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_ap_ready == 1'b1)) begin
            grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_seedInitialization_fu_40_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_seedInitialization_fu_40_ap_start_reg <= 1'b1;
        end else if ((grp_seedInitialization_fu_40_ap_ready == 1'b1)) begin
            grp_seedInitialization_fu_40_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        rngMT19937ICN_uniformRNG_x_k_p_0_V_reg_98 <= grp_seedInitialization_fu_40_ap_return_0;
        rngMT19937ICN_uniformRNG_x_k_p_1_V_reg_103 <= grp_seedInitialization_fu_40_ap_return_1;
        rngMT19937ICN_uniformRNG_x_k_p_2_V_reg_108 <= grp_seedInitialization_fu_40_ap_return_2;
        rngMT19937ICN_uniformRNG_x_k_p_m_V_reg_113 <= grp_seedInitialization_fu_40_ap_return_3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        H_rvd_address0 = grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_H_rvd_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        H_rvd_address0 = grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_H_rvd_address0;
    end else begin
        H_rvd_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        H_rvd_address1 = grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_H_rvd_address1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        H_rvd_address1 = grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_H_rvd_address1;
    end else begin
        H_rvd_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        H_rvd_ce0 = grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_H_rvd_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        H_rvd_ce0 = grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_H_rvd_ce0;
    end else begin
        H_rvd_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        H_rvd_ce1 = grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_H_rvd_ce1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        H_rvd_ce1 = grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_H_rvd_ce1;
    end else begin
        H_rvd_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        H_rvd_we0 = grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_H_rvd_we0;
    end else begin
        H_rvd_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        H_rvd_we1 = grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_H_rvd_we1;
    end else begin
        H_rvd_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        Hi_address0 = grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_Hi_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Hi_address0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_Hi_address0;
    end else begin
        Hi_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        Hi_ce0 = grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_Hi_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Hi_ce0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_Hi_ce0;
    end else begin
        Hi_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        Hi_we0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_Hi_we0;
    end else begin
        Hi_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        Hr_address0 = grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_Hr_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Hr_address0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_Hr_address0;
    end else begin
        Hr_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        Hr_ce0 = grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_Hr_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Hr_ce0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_Hr_ce0;
    end else begin
        Hr_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        Hr_we0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_Hr_we0;
    end else begin
        Hr_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_seedInitialization_fu_40_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_118_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_118_p_ce;
    end else begin
        grp_fu_118_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_122_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_122_p_ce;
    end else begin
        grp_fu_122_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_126_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_126_p_ce;
    end else begin
        grp_fu_126_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_130_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_130_p_ce;
    end else begin
        grp_fu_130_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_134_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_134_p_ce;
    end else begin
        grp_fu_134_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_138_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_138_p_ce;
    end else begin
        grp_fu_138_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_142_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_142_p_ce;
    end else begin
        grp_fu_142_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_146_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_146_p_ce;
    end else begin
        grp_fu_146_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_150_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_150_p_ce;
    end else begin
        grp_fu_150_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_154_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_154_p_ce;
    end else begin
        grp_fu_154_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_158_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_158_p_ce;
    end else begin
        grp_fu_158_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_162_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_162_p_ce;
    end else begin
        grp_fu_162_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_166_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_166_p_ce;
    end else begin
        grp_fu_166_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_170_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_170_p_ce;
    end else begin
        grp_fu_170_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_174_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_174_p_ce;
    end else begin
        grp_fu_174_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_178_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_178_p_ce;
    end else begin
        grp_fu_178_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_182_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_182_p_ce;
    end else begin
        grp_fu_182_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_186_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_186_p_ce;
    end else begin
        grp_fu_186_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_190_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_190_p_ce;
    end else begin
        grp_fu_190_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_194_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_194_p_ce;
    end else begin
        grp_fu_194_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_198_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_198_p_ce;
    end else begin
        grp_fu_198_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_202_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_202_p_ce;
    end else begin
        grp_fu_202_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_206_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_206_p_ce;
    end else begin
        grp_fu_206_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_210_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_210_p_ce;
    end else begin
        grp_fu_210_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_214_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_214_p_ce;
    end else begin
        grp_fu_214_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_218_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_218_p_ce;
    end else begin
        grp_fu_218_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_222_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_222_p_ce;
    end else begin
        grp_fu_222_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_226_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_226_p_ce;
    end else begin
        grp_fu_226_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_230_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_230_p_ce;
    end else begin
        grp_fu_230_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_234_ce = grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_grp_fu_234_p_ce;
    end else begin
        grp_fu_234_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_address0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_even_0_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_address0 = grp_seedInitialization_fu_40_this_mt_even_0_address0;
    end else begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_ce0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_even_0_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_ce0 = grp_seedInitialization_fu_40_this_mt_even_0_ce0;
    end else begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_ce1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_even_0_V_ce1;
    end else begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_d0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_even_0_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_d0 = grp_seedInitialization_fu_40_this_mt_even_0_d0;
    end else begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_we0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_even_0_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_we0 = grp_seedInitialization_fu_40_this_mt_even_0_we0;
    end else begin
        rngMT19937ICN_uniformRNG_mt_even_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_address0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_odd_0_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_address0 = grp_seedInitialization_fu_40_this_mt_odd_0_address0;
    end else begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_address1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_odd_0_V_address1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_address1 = grp_seedInitialization_fu_40_this_mt_odd_0_address1;
    end else begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_ce0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_odd_0_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_ce0 = grp_seedInitialization_fu_40_this_mt_odd_0_ce0;
    end else begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_ce1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_odd_0_V_ce1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_ce1 = grp_seedInitialization_fu_40_this_mt_odd_0_ce1;
    end else begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_d0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_odd_0_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_d0 = grp_seedInitialization_fu_40_this_mt_odd_0_d0;
    end else begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_we0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_rngMT19937ICN_uniformRNG_mt_odd_0_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_we0 = grp_seedInitialization_fu_40_this_mt_odd_0_we0;
    end else begin
        rngMT19937ICN_uniformRNG_mt_odd_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_seedInitialization_fu_40_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign H_mul_x_address0 = grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_H_mul_x_address0;

assign H_mul_x_ce0 = grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_H_mul_x_ce0;

assign H_mul_x_d0 = grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_H_mul_x_d0;

assign H_mul_x_we0 = grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_H_mul_x_we0;

assign H_rvd_d0 = grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_H_rvd_d0;

assign H_rvd_d1 = grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_H_rvd_d1;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_NS_fsm_state3 = ap_NS_fsm[32'd2];

assign grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_ap_start = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_ap_start_reg;

assign grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_ap_start = grp_Rayleigh_Pipeline_VITIS_LOOP_39_3_VITIS_LOOP_40_4_fu_66_ap_start_reg;

assign grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_ap_start = grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_ap_start_reg;

assign grp_fu_1001_p_ce = grp_fu_154_ce;

assign grp_fu_1001_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_154_p_din0;

assign grp_fu_1001_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_154_p_din1;

assign grp_fu_1001_p_opcode = 2'd0;

assign grp_fu_1005_p_ce = grp_fu_158_ce;

assign grp_fu_1005_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_158_p_din0;

assign grp_fu_1005_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_158_p_din1;

assign grp_fu_1005_p_opcode = 2'd0;

assign grp_fu_1009_p_ce = grp_fu_162_ce;

assign grp_fu_1009_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_162_p_din0;

assign grp_fu_1009_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_162_p_din1;

assign grp_fu_1009_p_opcode = 2'd0;

assign grp_fu_1013_p_ce = grp_fu_166_ce;

assign grp_fu_1013_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_166_p_din0;

assign grp_fu_1013_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_166_p_din1;

assign grp_fu_1017_p_ce = grp_fu_170_ce;

assign grp_fu_1017_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_170_p_din0;

assign grp_fu_1017_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_170_p_din1;

assign grp_fu_1021_p_ce = grp_fu_174_ce;

assign grp_fu_1021_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_174_p_din0;

assign grp_fu_1021_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_174_p_din1;

assign grp_fu_1025_p_ce = grp_fu_178_ce;

assign grp_fu_1025_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_178_p_din0;

assign grp_fu_1025_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_178_p_din1;

assign grp_fu_1029_p_ce = grp_fu_182_ce;

assign grp_fu_1029_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_182_p_din0;

assign grp_fu_1029_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_182_p_din1;

assign grp_fu_1033_p_ce = grp_fu_186_ce;

assign grp_fu_1033_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_186_p_din0;

assign grp_fu_1033_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_186_p_din1;

assign grp_fu_1037_p_ce = grp_fu_190_ce;

assign grp_fu_1037_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_190_p_din0;

assign grp_fu_1037_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_190_p_din1;

assign grp_fu_1041_p_ce = grp_fu_194_ce;

assign grp_fu_1041_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_194_p_din0;

assign grp_fu_1041_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_194_p_din1;

assign grp_fu_1045_p_ce = grp_fu_198_ce;

assign grp_fu_1045_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_198_p_din0;

assign grp_fu_1045_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_198_p_din1;

assign grp_fu_1049_p_ce = grp_fu_202_ce;

assign grp_fu_1049_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_202_p_din0;

assign grp_fu_1049_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_202_p_din1;

assign grp_fu_1053_p_ce = grp_fu_206_ce;

assign grp_fu_1053_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_206_p_din0;

assign grp_fu_1053_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_206_p_din1;

assign grp_fu_1057_p_ce = grp_fu_210_ce;

assign grp_fu_1057_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_210_p_din0;

assign grp_fu_1057_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_210_p_din1;

assign grp_fu_1061_p_ce = grp_fu_214_ce;

assign grp_fu_1061_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_214_p_din0;

assign grp_fu_1061_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_214_p_din1;

assign grp_fu_1065_p_ce = grp_fu_218_ce;

assign grp_fu_1065_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_218_p_din0;

assign grp_fu_1065_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_218_p_din1;

assign grp_fu_1069_p_ce = grp_fu_222_ce;

assign grp_fu_1069_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_222_p_din0;

assign grp_fu_1069_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_222_p_din1;

assign grp_fu_1073_p_ce = grp_fu_226_ce;

assign grp_fu_1073_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_226_p_din0;

assign grp_fu_1073_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_226_p_din1;

assign grp_fu_1077_p_ce = grp_fu_230_ce;

assign grp_fu_1077_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_230_p_din0;

assign grp_fu_1077_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_230_p_din1;

assign grp_fu_1081_p_ce = grp_fu_234_ce;

assign grp_fu_1081_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_grp_fu_234_p_din0;

assign grp_fu_1081_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_67_6_fu_74_grp_fu_234_p_din1;

assign grp_fu_1081_p_opcode = 2'd0;

assign grp_fu_965_p_ce = grp_fu_118_ce;

assign grp_fu_965_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_118_p_din0;

assign grp_fu_965_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_118_p_din1;

assign grp_fu_965_p_opcode = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_118_p_opcode;

assign grp_fu_969_p_ce = grp_fu_122_ce;

assign grp_fu_969_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_122_p_din0;

assign grp_fu_969_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_122_p_din1;

assign grp_fu_969_p_opcode = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_122_p_opcode;

assign grp_fu_973_p_ce = grp_fu_126_ce;

assign grp_fu_973_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_126_p_din0;

assign grp_fu_973_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_126_p_din1;

assign grp_fu_973_p_opcode = 2'd0;

assign grp_fu_977_p_ce = grp_fu_130_ce;

assign grp_fu_977_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_130_p_din0;

assign grp_fu_977_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_130_p_din1;

assign grp_fu_977_p_opcode = 2'd0;

assign grp_fu_981_p_ce = grp_fu_134_ce;

assign grp_fu_981_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_134_p_din0;

assign grp_fu_981_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_134_p_din1;

assign grp_fu_981_p_opcode = 2'd0;

assign grp_fu_985_p_ce = grp_fu_138_ce;

assign grp_fu_985_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_138_p_din0;

assign grp_fu_985_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_138_p_din1;

assign grp_fu_985_p_opcode = 2'd0;

assign grp_fu_989_p_ce = grp_fu_142_ce;

assign grp_fu_989_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_142_p_din0;

assign grp_fu_989_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_142_p_din1;

assign grp_fu_989_p_opcode = 2'd0;

assign grp_fu_993_p_ce = grp_fu_146_ce;

assign grp_fu_993_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_146_p_din0;

assign grp_fu_993_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_146_p_din1;

assign grp_fu_993_p_opcode = 2'd0;

assign grp_fu_997_p_ce = grp_fu_150_ce;

assign grp_fu_997_p_din0 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_150_p_din0;

assign grp_fu_997_p_din1 = grp_Rayleigh_Pipeline_VITIS_LOOP_28_1_VITIS_LOOP_29_2_fu_54_grp_fu_150_p_din1;

assign grp_fu_997_p_opcode = 2'd0;

assign grp_seedInitialization_fu_40_ap_start = grp_seedInitialization_fu_40_ap_start_reg;

endmodule //TOP_Rayleigh
